### ISSUE TITLE
Jagged saw-like artifacts in the high-res shape when generating training data

### ISSUE THREAD

**Issue by lzhengning** [HTDerekLiu/neuralSubdiv#1]
Hi, thanks for publishing the source code of your great work. I tried the examples and the result looks amazing. 

After that I tried to generate some more training data. I found that when simplifying an initial mesh into an extremely low-res mesh, there will be jagged artifacts in the fine meshes after upsampling. 

Take the end of a curved stick as an example. The original mesh has around 2000 vertices and 5000 faces. There are 10 vertices and 16 faces in the coarse mesh. Then upsample the coarse mesh with 3 iterations to get the fine mesh. 

- The original mesh
![snapshot05](https://user-images.githubusercontent.com/6365477/93445549-9ea43080-f903-11ea-90f6-74001e182361.png)

- The coarse mesh after simplification
![snapshot02](https://user-images.githubusercontent.com/6365477/93445598-a2d04e00-f903-11ea-83d7-a0ec6cb8d4e7.png)

- The fine mesh
![snapshot03](https://user-images.githubusercontent.com/6365477/93445629-a49a1180-f903-11ea-9cac-1fb28575a928.png)

The fine shape looks a little strange at the end and the surface normals are inconsistent. Is it caused by over simplification? Or potential failures with local parameterization?

Here are the obj files. https://drive.google.com/drive/folders/1hiVAv4OVZEkOCHP6iWesrK-eHE0mv8fD?usp=sharing

**Comment by HTDerekLiu** [comment]
Thanks for trying out neural subdivision :) 

Unfortunately, this is a limitation of the local parameterization. We use conformal maps to compute it and conformal maps preserve angles but not scales. Thus if the simplification is very aggressive, you may have a big region on the original mesh gets mapped to a tiny region on the coarse mesh. In that case, you may get artifacts due to not having enough upsampled vertices locally or numerical issues.

**Comment by lzhengning** [comment]
Thanks for responding!
