### ISSUE TITLE
Is there implementation available for MAPS in Appendix D

### ISSUE THREAD

**Issue by jiangzhongshi** [HTDerekLiu/neuralSubdiv#2]
Hi,

Thanks for the work and the code. I wonder if there is some pointer to the implementation of Maps, as in Appendix D?

**Comment by HTDerekLiu** [comment]
Hi, 

I couldn't find an existing implementation online, so I only have my (slow) reimplementation. Roughly speaking, you will need to change the `SSP_decimation.m` to do _vertex removal_, instead of edge collapses. The vertices get removed at each level is a maximum independent set. The rest of the "MAPS" will be very similar to neural subdivision!

**Comment by jiangzhongshi** [comment]
Thanks for the prompt response, if I understand correctly, the major
difference is DK vs. QSlim and the conformal map is similarly
used?

**Comment by HTDerekLiu** [comment]
Correct!
